# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6132b983595860a61bd4077a63f905fcbdb3cb7dc7296747b91d0de0a909c893c81040821bd8b56c845ef6c5a9f2a50a60759ce3880951d34ea1fec9ded38a1

test:
  secret_key_base: 39033c77f0252e05386ce21a444ca1de2a2cfbc3cc75aef18bbf7bc34ea2ec1d13d8961b9ad0a02309d96137094af4db1ab9532d7a32d09c718e33b5c13fa31d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
